apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  labels:
    app: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana_image
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
      volumes:
      - name: grafana
        configMap:
          name: grafana-conf
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: minikube
  labels:
    app: grafana
spec:
  externalTrafficPolicy: Cluster
  type: LoadBalancer
  loadBalancerIP: 192.168.99.100
  selector:
    app: grafana
  ports:
  - port: 3000
    name: http
    protocol: TCP
    targetPort: 3000
# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: grafana-conf
#   labels:
#     app: grafana
# data:
#   grafana.ini: |
#     [security]
#     disable_initial_admin_creation = true
#     admin_user = lelsweyr
#     admin_password = root